// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gklpmykcssoyzdcvqyow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbHBteWtjc3NveXpkY3ZxeW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzM0NDYsImV4cCI6MjA1OTUwOTQ0Nn0.gLO5G8P-u_JXDzvUAGkaLUkPG68GjD-nfy5NhgLuvNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);